import test from 'node:test';
import assert from 'node:assert/strict';
import { sampleWorld, advanceTime, samplePath, activeAlerts, createAlert, recordAlertAction } from '../src/simulation.ts';
import campus from '../public/data/campus.json' with {type:'json'};
test('replay gives identical actors and occupancy at the same timestamp',()=>{const a=sampleWorld(120);sampleWorld(400);assert.deepEqual(sampleWorld(120),a);});
test('paused clock stays fixed, speed and timeline boundaries are honored',()=>{assert.equal(advanceTime(30,5,false,4),30);assert.equal(advanceTime(30,5,true,4),50);assert.equal(advanceTime(899,5,true,4),900);});
test('parking count matches parked actors and never exceeds capacity',()=>{for(let t=0;t<=900;t+=7){const s=sampleWorld(t);assert.equal(s.parked,s.cars.filter(c=>c.parked).length);assert.ok(s.parked<=84);const ids=s.cars.filter(c=>c.parked).map(c=>c.slot);assert.equal(ids.length,new Set(ids).size);}});
test('all moving actors remain finite and vehicle trajectories are continuous',()=>{for(let t=0;t<900;t+=.9){const a=sampleWorld(t),b=sampleWorld(t+.1);a.cars.forEach((v,i)=>{assert.ok(Number.isFinite(v.x+v.z));assert.ok(Math.hypot(v.x-b.cars[i].x,v.z-b.cars[i].z)<3);});}});
test('path sampling follows distance, handles empty and single point',()=>{assert.deepEqual(samplePath([],0),{x:0,z:0,angle:0});assert.equal(samplePath([[2,3]],10).x,2);assert.equal(samplePath([[0,0],[10,0],[10,10]],15).z,5);});
test('alert acknowledgment and resolution only apply after their timestamps',()=>{const a=createAlert('international',50,0);a.ackAt=80;a.resolvedAt=100;assert.equal(activeAlerts([a],49).length,0);assert.equal(activeAlerts([a],60)[0].status,'待处理');assert.equal(activeAlerts([a],90)[0].status,'已确认');assert.equal(activeAlerts([a],110)[0].status,'已解除');});
test('replay cannot overwrite an already recorded operator action',()=>{const a=createAlert('international',50,0);recordAlertAction(a,'ack',120);recordAlertAction(a,'resolve',200);recordAlertAction(a,'resolve',150);assert.equal(activeAlerts([a],175)[0].status,'已确认');});
function inside(x:number,z:number,p:number[][]){let yes=false;for(let i=0,j=p.length-1;i<p.length;j=i++){if((p[i][1]>z)!==(p[j][1]>z)&&x<(p[j][0]-p[i][0])*(z-p[i][1])/(p[j][1]-p[i][1])+p[i][0])yes=!yes;}return yes;}
test('walking and driving routes do not pass through building footprints',()=>{for(let t=0;t<900;t+=3){const s=sampleWorld(t);for(const actor of [...s.cars,...s.people])for(const b of campus.buildings)assert.ok(!inside(actor.x,actor.z,b.polygon),`${actor.id} enters ${b.id} at ${t}s (${actor.x},${actor.z})`);}});
test('screenshot-derived road centerlines do not cross a building',()=>{for(const road of campus.roads.filter(r=>r.source!=='OSM'))for(let i=1;i<road.points.length;i++){const a=road.points[i-1],b=road.points[i],length=Math.hypot(a[0]-b[0],a[1]-b[1]);for(let s=0;s<=length;s+=1){const x=a[0]+(b[0]-a[0])*s/length,z=a[1]+(b[1]-a[1])*s/length;for(const building of campus.buildings)assert.ok(!inside(x,z,building.polygon),`${road.name} intersects ${building.id} at (${x},${z})`);}}});
