<script setup lang="ts">
import { computed,onMounted,onBeforeUnmount,ref,watch } from 'vue';
import { Box,Search,Layers,Building2,Car,Users,Activity,Sun,Moon,Maximize2,RotateCcw,MapPin,ChevronRight,Play,Pause,SkipBack,AlertTriangle,X,Check,Clock3,Navigation,LocateFixed,Info,TreePine,Route,PanelLeftClose,PanelLeftOpen,PanelRightClose,PanelRightOpen,Radio,ArrowUpRight,Zap,ParkingCircle,CheckCheck,Eye } from 'lucide-vue-next';
import campus from '../public/data/campus.json' with {type:'json'};
import provenance from '../public/data/osm-provenance.json';
import { createScene,type Layer } from './scene';
import { activeAlerts,advanceTime,createAlert,DURATION,sampleWorld,recordAlertAction,PEOPLE_COUNT,ACTOR_CAR_COUNT,type AlertRecord } from './simulation';
const host=ref<HTMLElement>();let viewer:ReturnType<typeof createScene>|undefined;
type ThemeMode='auto'|'day'|'night';
const wide=ref(!matchMedia('(max-width: 620px)').matches);
const ready=ref(false),error=ref(''),fps=ref(0),query=ref(''),category=ref('all'),selected=ref(''),tab=ref('overview'),themeMode=ref<ThemeMode>('auto'),night=ref(false),showSources=ref(false),sidebar=ref(wide.value),rightbar=ref(wide.value);
const playing=ref(!matchMedia('(prefers-reduced-motion: reduce)').matches),time=ref(120),speed=ref(1);let clock=120,raf=0,last=0,published=0;
const layers=ref<Record<Layer,boolean>>({trees:true,people:true,cars:true,labels:true,routes:false,osm:false});
const layerOptions:{key:Layer;label:string;icon:typeof TreePine}[]=[{key:'trees',label:'绿化树木',icon:TreePine},{key:'people',label:'模拟行人',icon:Users},{key:'cars',label:'模拟车辆',icon:Car},{key:'labels',label:'楼宇标注',icon:MapPin},{key:'routes',label:'行驶轨迹',icon:Route},{key:'osm',label:'OSM 轮廓',icon:Layers}];
const alerts=ref<AlertRecord[]>([createAlert('international',35,0),createAlert('equipment',85,1)]);
const snapshot=computed(()=>sampleWorld(time.value));
const events=computed(()=>activeAlerts(alerts.value,time.value).sort((a,b)=>b.at-a.at));
const openEvents=computed(()=>events.value.filter(e=>e.status!=='已解除'));
const building=computed(()=>campus.buildings.find(b=>b.id===selected.value));
const filtered=computed(()=>campus.buildings.filter(b=>(category.value==='all'||b.type===category.value)&&(`${b.name} ${b.id}`).toLowerCase().includes(query.value.toLowerCase())).sort((a,b)=>Number(b.type==='office')-Number(a.type==='office')));
const occupancy=computed(()=>Math.round(snapshot.value.parked/campus.parking.length*100));
const timeText=(t:number)=>`09:${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
const selectedLabel=computed(()=>building.value?.name||'全园区视角');
function focus(id:string){selected.value=id;viewer?.select(id);}
function view(name='overview'){selected.value='';viewer?.view(name);}
function seek(value:number){clock=Math.max(0,Math.min(DURATION,value));time.value=clock;viewer?.update(clock);}
function setTab(name:string){tab.value=name;if(name==='traffic'){layers.value.routes=true;viewer?.setLayer('routes',true);}else if(name==='overview'){layers.value.routes=false;viewer?.setLayer('routes',false);}}
function toggleLayer(key:Layer){layers.value[key]=!layers.value[key];viewer?.setLayer(key,layers.value[key]);}
function generateAlert(){const b=selected.value||['international','equipment','north-office'][alerts.value.length%3];alerts.value.push(createAlert(b,clock,alerts.value.length));tab.value='alerts';focus(b);}
function replay(a:AlertRecord){playing.value=false;seek(a.at);focus(a.buildingId);}
function acknowledge(id:string){const a=alerts.value.find(a=>a.id===id);if(a)recordAlertAction(a,'ack',clock);}
function resolve(id:string){const a=alerts.value.find(a=>a.id===id);if(a)recordAlertAction(a,'resolve',clock);}
function nameOf(id:string){return campus.buildings.find(b=>b.id===id)?.name||id;}
function onRange(e:Event){playing.value=false;seek(Number((e.target as HTMLInputElement).value));}
function play(){if(clock>=DURATION)seek(0);playing.value=!playing.value;}
function trend(i:number){return Array.from({length:30},(_,j)=>{const s=sampleWorld(j*30);return`${j*8},${60-(i?s.parked/campus.parking.length*45:(s.energy-155)/70*50)}`;}).join(' ');}
function nightFromClock(d=new Date()){const h=d.getHours();return h<6||h>=18;}
function applyThemeMode(){night.value=themeMode.value==='auto'?nightFromClock():themeMode.value==='night';}
function setThemeMode(mode:ThemeMode){themeMode.value=mode;applyThemeMode();}
function toggleNightManual(){setThemeMode(night.value?'day':'night');}
function setManual(){if(themeMode.value==='auto')setThemeMode(night.value?'night':'day');else toggleNightManual();}
async function load(){error.value='';ready.value=false;viewer?.destroy();if(!host.value)return;try{viewer=createScene(host.value,focus,v=>fps.value=v,e=>error.value=e);await viewer.ready;ready.value=true;viewer.setNight(night.value);for(const [k,v]of Object.entries(layers.value))viewer.setLayer(k as Layer,v);viewer.update(clock);viewer.setAlert(openEvents.value[0]?.buildingId);}catch(e){error.value=error.value||`无法启动 WebGL 场景：${String(e)}`;}}
watch(night,v=>{viewer?.setNight(v);document.documentElement.dataset.theme=v?'night':'day';});
watch(openEvents,v=>viewer?.setAlert(v[0]?.buildingId),{deep:true});
function animate(now:number){const dt=last?Math.min((now-last)/1000,.25):0;last=now;clock=advanceTime(clock,dt,playing.value&&ready.value,speed.value);viewer?.update(clock);if(now-published>180){time.value=clock;published=now;}if(clock>=DURATION)playing.value=false;raf=requestAnimationFrame(animate);}
function onKey(e:KeyboardEvent){if(e.key==='Escape')showSources.value=false;}
let themeTimer=0;
onMounted(()=>{applyThemeMode();load();raf=requestAnimationFrame(animate);window.addEventListener('keydown',onKey);themeTimer=window.setInterval(()=>{if(themeMode.value==='auto')applyThemeMode();},60_000);});
onBeforeUnmount(()=>{cancelAnimationFrame(raf);clearInterval(themeTimer);viewer?.destroy();window.removeEventListener('keydown',onKey);});
function fullscreen(){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else document.documentElement.requestFullscreen().catch(()=>{error.value='当前浏览器不支持全屏，请使用窗口最大化。';});}
</script>

<template>
  <div class="app-shell" :data-theme="night?'night':'day'">
    <header class="topbar">
      <a class="brand" href="/" aria-label="六号院数字孪生首页"><span class="brand-mark"><Box :size="25" :stroke-width="1.5"/></span><span><strong>六号院 <span class="brand-divider">/</span> 数字孪生</strong><small>河北 · 涿州 · 平安小区</small></span></a>
      <nav class="main-nav" aria-label="主导航"><button :class="{active:tab==='overview'}" @click="setTab('overview')"><Box :size="16"/>场景总览</button><button :class="{active:tab==='traffic'}" @click="setTab('traffic')"><Route :size="16"/>交通运行</button><button :class="{active:tab==='alerts'}" @click="setTab('alerts')"><Radio :size="16"/>事件中心<span class="nav-count">{{openEvents.length}}</span></button></nav>
      <div class="header-status"><span class="sim-badge"><i/>模拟运行</span><div class="date"><b>{{timeText(time)}}</b><span>2026 / 09 / 20</span></div><button class="icon-button source-button" aria-label="查看数据来源" @click="showSources=true"><Info :size="19"/></button></div>
    </header>

    <main class="workspace" :class="{'left-collapsed':!sidebar,'right-collapsed':!rightbar}">
      <aside class="left-panel" v-show="sidebar">
        <div class="panel-title"><span><Building2 :size="17"/>园区资产</span><button class="icon-button" aria-label="收起资产面板" @click="sidebar=false"><PanelLeftClose :size="16"/></button></div>
        <div class="search-field"><Search :size="16"/><input v-model="query" placeholder="搜索楼宇名称 / 编号" aria-label="搜索楼宇"/><button v-if="query" @click="query=''" class="icon-button" aria-label="清空搜索"><X :size="13"/></button></div>
        <div class="filter-tabs"><button v-for="(label,key) in {all:'全部',office:'办公',residential:'住宅',service:'配套',factory:'厂房'}" :key="key" :class="{active:category===key}" @click="category=key">{{label}}</button></div>
        <div class="asset-heading"><span>建筑列表</span><span>{{filtered.length}} 栋</span></div>
        <div class="building-list"><button v-for="b in filtered" :key="b.id" class="asset-row" :class="{selected:selected===b.id}" @click="focus(b.id)"><span class="asset-icon" :class="b.type"><Building2 :size="18"/></span><span class="asset-name"><strong>{{b.name}}</strong><small>{{b.type==='office'?'办公建筑':b.type==='residential'?'住宅建筑':b.type==='factory'?'厂房建筑':'配套建筑'}} <span>·</span> {{b.floors}} 层{{b.floorsConfirmed?'（已确认）':'（估）'}}</small></span><ChevronRight :size="14"/></button><div class="empty-state" v-if="!filtered.length">未找到匹配楼宇<br><small>试试“国际部”或“住宅楼”</small></div></div>
        <section class="layer-section"><div class="section-heading"><span><Layers :size="16"/>场景图层</span><span>{{Object.values(layers).filter(Boolean).length}} 已开启</span></div><button class="layer-row" v-for="layer in layerOptions" :key="layer.key" @click="toggleLayer(layer.key)" :aria-pressed="layers[layer.key]"><span><component :is="layer.icon" :size="15"/>{{layer.label}}</span><span class="toggle" :class="{on:layers[layer.key]}"><i/></span></button></section>
        <button class="source-card" @click="showSources=true"><span class="source-symbol"><Layers :size="18"/></span><span><strong>空间数据来源</strong><small>OpenStreetMap · 2026.09.20</small></span><ArrowUpRight :size="15"/></button>
      </aside>

      <section class="scene-section" aria-label="三维园区场景">
        <div class="scene-canvas" ref="host"></div>
        <div class="scene-top"><div class="view-badge"><button v-if="!sidebar" class="icon-button" aria-label="展开资产面板" @click="sidebar=true"><PanelLeftOpen :size="17"/></button><span class="tiny-square"/>{{selectedLabel}}<span class="view-tag">3D</span></div><div class="theme-controls"><button v-if="!rightbar" class="icon-button theme-reopen" aria-label="展开运行概览" title="展开运行概览" @click="rightbar=true"><PanelRightOpen :size="17"/></button><div class="weather"><component :is="night?Moon:Sun" :size="17"/><span>{{night?'夜间场景':'日间场景'}} · {{themeMode==='auto'?'自动':'手动'}}</span></div><div class="theme-switch" role="group" aria-label="页面风格切换"><button type="button" :class="{active:themeMode==='day'}" @click="setThemeMode('day')">日间</button><button type="button" :class="{active:themeMode==='night'}" @click="setThemeMode('night')">夜间</button><button type="button" :class="{active:themeMode!=='auto'}" @click="setManual">手动</button><button type="button" :class="{active:themeMode==='auto'}" @click="setThemeMode('auto')">自动</button></div></div></div>
        <div v-if="!ready&&!error" class="loading-overlay"><span class="loader"/><strong>正在构建园区视野</strong><span>加载 Blender 模型与场景资产</span></div>
        <div v-if="error" class="error-overlay"><AlertTriangle/><strong>场景暂不可用</strong><p>{{error}}</p><button class="primary-button" @click="load">重新加载</button></div>
        <div class="scene-tools"><button class="tool-button" @click="view()" aria-label="恢复全园区视角" title="全园区"><RotateCcw :size="18"/></button><button class="tool-button" @click="view('top')" aria-label="俯视园区" title="俯视"><Layers :size="18"/></button><button class="tool-button" @click="view('south')" aria-label="查看南侧办公区" title="南侧办公区"><Building2 :size="18"/></button><span/><button class="tool-button" @click="toggleNightManual" :aria-label="night?'切换日间':'切换夜间'" :title="night?'切换日间':'切换夜间'"><component :is="night?Sun:Moon" :size="18"/></button><button class="tool-button" @click="fullscreen" aria-label="切换全屏" title="全屏"><Maximize2 :size="18"/></button></div>
        <div class="north-indicator"><span>N</span><Navigation :size="24" :stroke-width="1.3"/><span class="compass-caption">正北参考</span></div>
        <div class="scene-caption"><span class="scene-caption-dot"/>地理轮廓还原 · 建筑立面近似重建</div>
        <div class="map-card"><div class="map-title"><span>园区导航</span><LocateFixed :size="13"/></div><svg viewBox="-335 -290 675 580" role="img" aria-label="园区建筑缩略图，点击楼宇定位"><rect x="-330" y="-285" width="670" height="570" rx="15" fill="#273c42"/><path d="M-82,-225V150M166,-225V150M-280,27H295M-82,146H166M-32.6,195V240" stroke="#4b5c5b" stroke-width="8" fill="none"/><rect v-for="g in campus.greens" :key="g.id" :x="g.x-g.w/2" :y="g.z-g.d/2" :width="g.w" :height="g.d" fill="#3d5a3a" opacity=".85"/><rect v-for="b in campus.buildings" :key="b.id" :x="b.x-b.w/2" :y="b.z-b.d/2" :width="b.w" :height="b.d" :fill="selected===b.id?'#81eed1':b.type==='office'?'#68b6a7':b.type==='factory'?'#a8946a':'#738782'" @click="focus(b.id)"><title>{{b.name}}</title></rect><circle v-if="building" :cx="building.x" :cy="building.z" r="23" fill="none" stroke="#b0ffe8" stroke-width="3"/></svg><div class="map-scale"><span/><small>约 100 m</small></div></div>
        <div class="scene-bottom"><span><span class="status-dot"/>{{ready?'WebGL 已连接':'场景加载中'}}<b>{{fps}} FPS</b></span><span class="scene-help">左键旋转 / 右键平移 / 滚轮缩放</span><a class="osm-credit" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap contributors</a></div>
      </section>

      <aside class="right-panel" v-show="rightbar">
        <div class="panel-title"><span><Activity :size="17"/>{{tab==='traffic'?'交通运行':tab==='alerts'?'事件中心':'运行概览'}}</span><span class="panel-title-actions"><span class="muted small">模拟数据</span><button class="icon-button" aria-label="收起运行概览" title="收起运行概览" @click="rightbar=false"><PanelRightClose :size="16"/></button></span></div>
        <div class="metric-grid"><div class="metric"><div><Building2 :size="16"/><span>场景建筑</span></div><p>{{campus.buildings.length}}<small>栋</small></p><span class="metric-note">含 {{campus.buildings.filter(b=>b.type==='office').length}} 栋办公建筑</span></div><div class="metric"><div><Users :size="16"/><span>行人 / 骑行</span></div><p>{{snapshot.people.length}}<small>人</small></p><span class="metric-note">步行 {{snapshot.walkers}} · 自行车 {{snapshot.bikes}} · 电动车 {{snapshot.ebikes}}</span></div><div class="metric"><div><Car :size="16"/><span>园区车辆</span></div><p>{{snapshot.cars.length}}<small>辆</small></p><span class="metric-note">{{snapshot.moving}} 辆行驶中（含范阳中路）</span></div><div class="metric"><div><ParkingCircle :size="16"/><span>车位占用</span></div><p>{{occupancy}}<small>%</small></p><span class="metric-note">{{snapshot.parked}} / {{campus.parking.length}} 个车位</span></div></div>

        <section class="detail-card" v-if="building"><div class="section-heading"><span><MapPin :size="15"/>楼宇档案</span><button class="icon-button" aria-label="关闭楼宇档案" @click="selected='' "><X :size="14"/></button></div><h2>{{building.name}}</h2><div class="detail-tags"><span>{{building.type==='office'?'办公':building.type==='residential'?'住宅':building.type==='factory'?'厂房':'配套'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>{{building.floors}} 层{{building.floorsConfirmed?'（已确认）':'（估）'}}</span><span>高度约 {{building.height}} m</span></div><p>{{building.source}}</p><button class="text-action" @click="focus(building.id)"><LocateFixed :size="13"/>重新定位</button></section>

        <section class="parking-section" v-if="tab==='traffic'"><div class="section-heading"><span>停车场状态</span><span>{{campus.parking.length-snapshot.parked}} 空余</span></div><div class="parking-grid"><span v-for="(p,i) in campus.parking" :key="p.id" :class="{occupied:snapshot.cars.some(c=>c.parked&&c.slot===i)}" :title="`${p.id} ${snapshot.cars.some(c=>c.parked&&c.slot===i)?'占用':'空闲'}`"/></div><div class="parking-legend"><span><i/>空闲</span><span><i/>占用</span></div></section>
        <section class="energy-section" v-else-if="tab==='overview'&&!building"><div class="section-heading"><span><Zap :size="15"/>模拟用电负荷</span><span>15 分钟</span></div><div class="energy-value">{{snapshot.energy}}<small>kW</small><span>园区汇总</span></div><svg class="trend-chart" viewBox="0 0 232 68" aria-label="模拟用电负荷趋势"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#6bd9c0" stop-opacity=".22"/><stop offset="100%" stop-color="#6bd9c0" stop-opacity="0"/></linearGradient></defs><path d="M0 20H232M0 45H232" stroke="#30404a" stroke-dasharray="3 4"/><polygon :points="'0,68 '+trend(0)+' 232,68'" fill="url(#area)"/><polyline :points="trend(0)" fill="none" stroke="#74d7bc" stroke-width="2"/><line :x1="time/900*232" y1="2" :x2="time/900*232" y2="68" stroke="#a9cec3" stroke-dasharray="2 3"/></svg><div class="chart-labels"><span>09:00</span><span>09:05</span><span>09:10</span><span>09:15</span></div></section>

        <section class="events-section"><div class="section-heading"><span><Radio :size="15"/>{{tab==='alerts'?'模拟事件记录':'园区事件'}}<b class="event-count">{{openEvents.length}}</b></span><span class="muted">{{events.length}} 条</span></div><div class="event-list"><article v-for="a in events" :key="a.id" class="event-card" :class="{resolved:a.status==='已解除'}"><div class="event-header"><span :class="['event-level',a.level]"><AlertTriangle :size="12"/>{{a.title}}</span><small>{{timeText(a.at)}}</small></div><button class="event-location" @click="focus(a.buildingId)">{{nameOf(a.buildingId)}}<ArrowUpRight :size="12"/></button><div class="event-footer"><span :class="{'done':a.status==='已解除'}">{{a.status}}</span><div><button v-if="a.status==='待处理'" @click="acknowledge(a.id)" :disabled="a.ackAt!==undefined" :title="a.ackAt!==undefined?'已在后续时间记录确认，请通过时间轴查看':'确认告警'" aria-label="确认告警"><Check :size="13"/>确认</button><button v-if="a.status==='已确认'" @click="resolve(a.id)" :disabled="a.resolvedAt!==undefined" :title="a.resolvedAt!==undefined?'已在后续时间记录解除，请通过时间轴查看':'解除告警'"><CheckCheck :size="13"/>解除</button><button @click="replay(a)"><Clock3 :size="12"/>回放</button></div></div></article><div class="empty-state" v-if="!events.length"><CheckCheck :size="22"/><p>当前时刻暂无事件</p></div></div><button class="simulate-button" @click="generateAlert"><Radio :size="15"/>触发模拟告警<span>＋</span></button></section>
        <div class="panel-footnote"><Info :size="13"/><span>人员、车辆、运行指标及告警均为模拟。</span></div>
      </aside>
    </main>

    <footer class="replay-bar"><div class="replay-title"><span class="replay-symbol"><Clock3 :size="20"/></span><span><strong>时空回放</strong><small>{{playing?'模拟时间推进中':'已暂停 · 可拖动时间轴'}}</small></span></div><div class="play-controls"><button class="icon-button" aria-label="回到起点" @click="seek(0)"><SkipBack :size="17"/></button><button class="play-button" @click="play" :aria-label="playing?'暂停模拟':'播放模拟'"><component :is="playing?Pause:Play" :size="18" fill="currentColor"/></button><select v-model.number="speed" aria-label="回放速度"><option :value="1">1×</option><option :value="2">2×</option><option :value="4">4×</option><option :value="8">8×</option></select></div><div class="timeline"><div class="timeline-ticks"><span v-for="v in ['09:00','09:03','09:06','09:09','09:12','09:15']" :key="v">{{v}}</span></div><div class="timeline-track"><input type="range" min="0" :max="DURATION" step=".1" :value="time" @input="onRange" aria-label="回放时间轴" :style="{'--progress':time/DURATION*100+'%'}"/><button v-for="a in alerts" :key="a.id" class="event-marker" :style="{left:a.at/DURATION*100+'%'}" @click="replay(a)" :aria-label="`回放${nameOf(a.buildingId)}${a.title}`" :title="`${timeText(a.at)} ${a.title}`"/></div></div><div class="replay-clock"><b>{{timeText(time)}}</b><span>2026 年 09 月 20 日</span></div></footer>
    <div class="source-modal-backdrop" v-if="showSources" @click.self="showSources=false"><section class="source-modal" role="dialog" aria-modal="true" aria-labelledby="source-title"><button class="modal-close icon-button" aria-label="关闭数据来源" @click="showSources=false"><X/></button><span class="modal-emblem"><Layers :size="27"/></span><h2 id="source-title">数据与重建依据</h2><p class="modal-intro">把真实的空间依据与近似建模、模拟运行清晰区分。</p><dl><dt>OpenStreetMap</dt><dd>导入时间：{{provenance.importedAt}}<br>数据时间：{{provenance.osmTimestamp}}<br>院区建筑与园路已按该 OSM 轮廓更新<br><a href="/data/osm-2026-09-21.json" download>下载 OSM JSON</a><a href="/data/osm-2026-09-21.osm.xml" download>下载原始 OSM XML</a><a href="/data/osm-provenance.json" download>下载来源记录</a></dd><dt>办公楼位置</dt><dd>国际部大楼采用 OSM way 1560982331 真实轮廓；厂房采用 way 390196198；装备专业化大楼采用 ways 1560982332+390196010 合并轮廓。国际部大楼中轴以南门引路直连范阳中路。可见立面依据实景照片；国际部 20 层、装备楼 6 层已确认；高度与未见立面仍为近似。</dd><dt>实景资料检索</dt><dd><a href="https://news.lianjia.com/bd/xiaoqu/5520027578204528.html" target="_blank" rel="noopener noreferrer">六号院公开外景资料 ↗</a><br>两栋重点楼的可见立面已依据您补充的实景照片重建。第二张仅展示入口局部，未见部分仍为近似。</dd><dt>模拟内容</dt><dd>{{PEOPLE_COUNT}} 名行人、{{ACTOR_CAR_COUNT}} 辆车、{{campus.parking.length}} 个模拟车位。交通与告警由统一的 15 分钟模拟时间轴驱动，不连接真实监控系统。</dd></dl><div class="license">© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a> · ODbL 1.0</div><button class="primary-button" @click="showSources=false">返回园区</button></section></div>
  </div>
</template>



